import LeanRegression.Design
import Mathlib.Probability.Moments.Basic

set_option linter.style.header false

/-!
# Linear estimators for a fixed design

Unbiasedness is encoded algebraically: a linear estimator is unbiased for every coefficient vector
and every centered error distribution precisely when it is a left inverse of the design.  The
adjoint formulation gives the corresponding condition for scalar contrasts.
-/

namespace LeanRegression

noncomputable section

open scoped RealInnerProductSpace
open MeasureTheory ProbabilityTheory

variable {P O : Type*}
  [NormedAddCommGroup P] [InnerProductSpace ℝ P] [CompleteSpace P]
  [FiniteDimensional ℝ P]
  [NormedAddCommGroup O] [InnerProductSpace ℝ O] [CompleteSpace O]

namespace FixedDesign

variable (D : FixedDesign P O)

/-- A response generated by the fixed-design linear model `Y = Xβ + ε`. -/
def response (β : P) (ε : O) : O :=
  D.map β + ε

/-- A linear estimator is unbiased for the design when it is a left inverse of the design map. -/
def IsLinearUnbiasedEstimator (A : O →L[ℝ] P) : Prop :=
  A ∘L D.map = ContinuousLinearMap.id ℝ P

/-- A weight vector estimates the scalar contrast represented by `c` without bias. -/
def IsUnbiasedContrast (c : P) (a : O) : Prop :=
  D.map.adjoint a = c

omit [CompleteSpace P] [FiniteDimensional ℝ P]
  [CompleteSpace O] in
theorem isLinearUnbiasedEstimator_iff (A : O →L[ℝ] P) :
    D.IsLinearUnbiasedEstimator A ↔ ∀ β, A (D.map β) = β := by
  constructor
  · intro h β
    exact DFunLike.congr_fun h β
  · intro h
    ext β
    exact h β

theorem ols_isLinearUnbiasedEstimator : D.IsLinearUnbiasedEstimator D.ols :=
  D.ols_comp_map

omit [CompleteSpace P] [FiniteDimensional ℝ P]
  [CompleteSpace O] in
theorem estimate_response (A : O →L[ℝ] P) (hA : D.IsLinearUnbiasedEstimator A)
    (β : P) (ε : O) :
    A (D.response β ε) = β + A ε := by
  rw [response, map_add, (D.isLinearUnbiasedEstimator_iff A).mp hA β]

omit [FiniteDimensional ℝ P] in
/-- The algebraic left-inverse condition implies the usual expectation-based unbiasedness for
every integrable centered error. -/
theorem integral_estimate_response {Ω : Type*} [MeasurableSpace Ω]
    {ν : Measure Ω} [IsProbabilityMeasure ν]
    (A : O →L[ℝ] P) (hA : D.IsLinearUnbiasedEstimator A)
    (β : P) (ε : Ω → O) (hε : Integrable ε ν) (hcentered : ∫ ω, ε ω ∂ν = 0) :
    ∫ ω, A (D.response β (ε ω)) ∂ν = β := by
  have hpointwise :
      (fun ω ↦ A (D.response β (ε ω))) = (fun ω ↦ β + A (ε ω)) := by
    funext ω
    exact D.estimate_response A hA β (ε ω)
  rw [hpointwise]
  rw [integral_add (integrable_const β) (A.integrable_comp hε),
    A.integral_comp_comm hε, hcentered]
  simp

omit [FiniteDimensional ℝ P] in
theorem unbiased_adjoint_weight (A : O →L[ℝ] P)
    (hA : D.IsLinearUnbiasedEstimator A) (c : P) :
    D.IsUnbiasedContrast c (A.adjoint c) := by
  change D.map.adjoint (A.adjoint c) = c
  calc
    D.map.adjoint (A.adjoint c) = (A ∘L D.map).adjoint c := by
      simp only [ContinuousLinearMap.adjoint_comp, ContinuousLinearMap.comp_apply]
    _ = (ContinuousLinearMap.id ℝ P).adjoint c := by rw [hA]
    _ = c := by rw [ContinuousLinearMap.adjoint_id]; rfl

/-- The observation-space weight vector representing the OLS estimate of a contrast. -/
def olsContrastWeight (c : P) : O :=
  D.ols.adjoint c

@[simp]
theorem olsContrastWeight_eq (c : P) :
    D.olsContrastWeight c = D.map (D.gramInverse c) := by
  rw [olsContrastWeight, D.ols_adjoint]
  rfl

theorem olsContrastWeight_unbiased (c : P) :
    D.IsUnbiasedContrast c (D.olsContrastWeight c) :=
  D.unbiased_adjoint_weight D.ols D.ols_isLinearUnbiasedEstimator c

theorem olsContrastWeight_mem_range (c : P) :
    D.olsContrastWeight c ∈ D.map.range := by
  exact ⟨D.gramInverse c, D.olsContrastWeight_eq c |>.symm⟩

theorem contrast_estimate_eq_inner (c : P) (y : O) :
    inner ℝ c (D.ols y) = inner ℝ (D.olsContrastWeight c) y := by
  exact D.ols.adjoint_inner_left y c |>.symm

end FixedDesign

end

end LeanRegression

